// One insights report as markdown, for filing into an issue tracker.
//
// GitHub's issue API cannot attach a PDF (nor can Linear's, for anything but
// images), so "send the report to the tracker" honestly means "the report IS
// the issue body" — the same shape a filed defect takes, minus the
// screenshots. Everything here comes from the STORED report: content that was
// summary-shaped and secret-redacted at generation, plus the deterministic
// stats the view's own strip renders. `createIssue` redacts the final body
// against the live secret set again on the way out, same as every filed
// defect.
//
// Pure, so the outgoing shape is assertable without a tracker.

import type { InsightReport } from "../../recorder/types.js";

const CADENCE_WORD: Record<InsightReport["cadence"], string> = {
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
};

function fmtDate(ms: number): string {
  return new Date(ms).toISOString().slice(0, 10);
}

/** The issue's default title. */
export function insightReportIssueTitle(report: InsightReport): string {
  return `${CADENCE_WORD[report.cadence]} testing report — ${fmtDate(report.generatedAt)}`;
}

/** The issue's default body. */
export function insightReportMarkdown(report: InsightReport): string {
  const lines: string[] = [];
  lines.push(`**${report.headline}**`);
  lines.push("");
  lines.push(
    `${CADENCE_WORD[report.cadence]} report · ${fmtDate(report.periodStart)} to ${fmtDate(report.periodEnd)} · written by ${report.provider} (${report.model})`,
  );
  if (report.degraded) {
    lines.push("");
    lines.push(
      "_The model's answer didn't follow the report format, so the text below is unstructured._",
    );
  }

  // The deterministic numbers, from the same stats the app's own strip
  // renders — never parsed back out of the prose. Null means the metrics DB
  // was unavailable at generation, and the row is omitted rather than zeroed.
  lines.push("");
  lines.push("| | |");
  lines.push("| --- | --- |");
  const stat = (label: string, value: number | null) => {
    if (value !== null) lines.push(`| ${label} | ${value} |`);
  };
  stat("Runs", report.stats.runs);
  stat("Failed", report.stats.failed);
  stat("Previous period", report.stats.previousRuns);
  stat("Possible flake", report.stats.flakyRuns);
  stat("Healed steps", report.stats.healedSteps);
  stat("Heal failures", report.stats.healFailures);
  stat("Visual changes", report.stats.visualChanges);
  stat("New failure signatures", report.stats.newClusters);
  stat("New a11y violations", report.stats.a11yNewSteps);
  stat("Tests created", report.stats.testsCreated);
  stat("Unreviewed changes", report.stats.unreviewedScriptChanges);
  stat("Signature warnings", report.stats.expiringSignatures);

  for (const section of report.sections) {
    lines.push("");
    if (section.title) {
      lines.push(`## ${section.title}`);
      lines.push("");
    }
    lines.push(section.body);
  }

  if (report.actions.length > 0) {
    lines.push("");
    lines.push("## Recommended");
    lines.push("");
    for (const action of report.actions) {
      // The label is the model's reason; the target renders as plain text.
      // No goodlooks:// links — an issue reader may not have the app.
      const target = action.testName ?? action.testId ?? "";
      lines.push(`- ${action.label}${target ? ` (${target})` : ""}`);
    }
  }

  lines.push("");
  lines.push(`_Generated by Good Looks! on ${fmtDate(report.generatedAt)}._`);
  return lines.join("\n");
}
