// The app's component library — the port's replacement for @glaze/core/components
// and @glaze/core/hooks. Every symbol the 36 consuming views import is exported
// here under its original name, so the views themselves were not rewritten:
// only their import specifier changed to "@ui".
//
// Layout of the implementation:
//   primitives.tsx  — single-element components (Button, Input, Text, Table…)
//   controls.tsx    — Radix form controls (Switch, Tabs, Slider, Tooltip…)
//   layout.tsx      — structure (Toolbar, ScrollArea, Field, Sidebar, SplitView)
//   overlays.tsx    — portalled UI (Dialog, AlertDialog, context menu, toasts)
//   native-menu.tsx — Select + DropdownMenu, still backed by real macOS menus

export { cn } from "./cn";
export { useTheme } from "./use-theme";

export {
  Badge,
  Button,
  Input,
  Label,
  Status,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
  Text,
  Textarea,
  badgeVariants,
  buttonVariants,
  textVariants,
  type BadgeColor,
  type BadgeProps,
  type ButtonProps,
  type TextProps,
} from "./primitives";

export {
  Checkbox,
  RadioGroup,
  RadioGroupItem,
  SegmentedControl,
  SegmentedControlItem,
  SegmentedControlSeparator,
  Slider,
  Switch,
  Tabs,
  TabsContent,
  TabsRoot,
  TabsSeparator,
  TabsTrigger,
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
  type SegmentedControlProps,
  type SliderProps,
  type TabsProps,
  type TooltipSide,
} from "./controls";

export {
  Callout,
  EmptyState,
  EmptyStateActions,
  EmptyStateDescription,
  EmptyStateMedia,
  EmptyStateTitle,
  ErrorBoundaryView,
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldTitle,
  ScrollArea,
  Sidebar,
  SidebarFooter,
  SidebarList,
  SidebarListGroup,
  SidebarListGroupTitle,
  SidebarListItem,
  SidebarListItemAccessory,
  SidebarListItemContent,
  SidebarListItemSubtitle,
  SidebarListItemTitle,
  SplitView,
  Toolbar,
  ToolbarActions,
  ToolbarBackButton,
  ToolbarContent,
  ToolbarDescription,
  ToolbarRow,
  ToolbarTitle,
  useSplitView,
  type CalloutProps,
  type ScrollAreaControl,
  type SlotSize,
  type SplitViewProps,
  type ToolbarProps,
} from "./layout";

export {
  AlertDialog,
  AlertDialogAction,
  AlertDialogBody,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogOverlay,
  AlertDialogPortal,
  AlertDialogTitle,
  AlertDialogTrigger,
  CustomContextMenu,
  CustomContextMenuCheckboxItem,
  CustomContextMenuContent,
  CustomContextMenuGroup,
  CustomContextMenuItem,
  CustomContextMenuLabel,
  CustomContextMenuPortal,
  CustomContextMenuRadioGroup,
  CustomContextMenuRadioItem,
  CustomContextMenuSeparator,
  CustomContextMenuShortcut,
  CustomContextMenuSub,
  CustomContextMenuSubContent,
  CustomContextMenuSubTrigger,
  CustomContextMenuTrigger,
  Dialog,
  DialogBody,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
  NativeDatePickerRoot,
  NativeDatePickerTrigger,
  NativeDatePickerValue,
  Toaster,
  toast,
} from "./overlays";

export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuSub,
  DropdownMenuTrigger,
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  type DropdownMenuAlign,
  type DropdownMenuSide,
  type NativeMenuIcon,
} from "./native-menu";
