// The spec runtime helper as a raw JS string, written next to the specs at
// runtime (like step-reporter-source.ts and capture-fixture-source.ts).
//
// Every helper here exists for the same structural reason: a step must emit
// exactly ONE awaited line. `buildStepLineMap` in playwright-runner classifies
// spec lines by a leading `await`, and Playwright's own reporter attributes a
// failure to a line; a statement neither of them recognizes as a step — or a
// step spanning several — would shift every later step's highlight and
// screenshot attribution.
//
//  • glazeCapture: a capture step's natural spelling —
//    `V.orderId = await page.getByTestId("order").textContent();` — starts
//    with `V.`, not `await`. Routing the assignment through an awaited call
//    keeps the line shaped like every other step's.
//  • glazeScrollTo: an incremental scroll is a LOOP, and a loop inlined into
//    the spec would be many lines for one step.
//
// Plain JavaScript (no TypeScript) because Playwright loads it through its own
// Babel transform, which does not understand `import type`.
//
//  • glazeA11yGate: the a11y GATE step — axe at this point in the test, FAIL
//    on new violations at/above the impact floor. Its decision logic is NOT
//    written here: `gateFailures` is imported from shared/a11y-rollup.mjs and
//    embedded via toString(), the step-semantics idiom, so the gate and the
//    app's baseline bookkeeping can never disagree about what a key means.

import { gateFailures } from "../../shared/a11y-rollup.mjs";

export const GLAZE_RUNTIME_FILE = "glaze-runtime.mjs";

export const glazeRuntimeSource = `// Generated by Good Looks! — do not edit.

/**
 * Read a value off the page into the run's variable scope.
 *
 * Writes an empty string rather than null/undefined when there is nothing to
 * read, so a later step interpolating the variable produces "" instead of the
 * literal text "null" — which would otherwise be typed into a field or
 * asserted against, and look like a real value in the log.
 */
export async function glazeCapture(vars, name, subject, from, attr) {
  let value = "";
  try {
    if (from === "url") {
      value = subject.url();
    } else if (from === "title") {
      value = await subject.title();
    } else if (from === "value") {
      value = await subject.inputValue();
    } else if (from === "attribute") {
      value = await subject.getAttribute(attr || "");
    } else if (from === "count") {
      // How many elements the locator matches — deliberately NOT a strict
      // resolve: counting an ambiguous or absent locator is the whole point
      // (0 is an answer, not a failure).
      value = String(await subject.count());
    } else {
      value = await subject.textContent();
    }
  } catch (err) {
    // A capture that fails must fail the step, not corrupt the scope with a
    // half-read value. Rethrow with the variable named, since "locator timeout"
    // alone doesn't say which capture broke.
    throw new Error("Could not capture \\"" + name + "\\": " + String(err));
  }
  vars[name] = value == null ? "" : String(value).trim();
  return vars[name];
}

/**
 * Scroll the window to an absolute page position, the way a person does:
 * in viewport-sized increments with a beat between them, so a page that
 * renders lazily (infinite scroll, IntersectionObserver-gated content) sees
 * scroll progression and has time to extend itself. A single jump to the
 * recorded offset would clamp at the CURRENT document height, which on a lazy
 * page is far short of where the user actually was.
 *
 * Stops when the target is reached, or when several consecutive rounds make
 * no progress — a page that is now shorter than it was at record time has
 * been scrolled as far as it goes, and that is not this step's failure to
 * report (the assertion after it will say what is missing).
 */
export async function glazeScrollTo(page, x, y) {
  let last = null;
  let stalls = 0;
  for (let i = 0; i < 120; i++) {
    const pos = await page.evaluate(([tx, ty]) => {
      const cap = Math.max(200, window.innerHeight * 0.8);
      const dx = Math.max(-cap, Math.min(cap, tx - window.scrollX));
      const dy = Math.max(-cap, Math.min(cap, ty - window.scrollY));
      window.scrollBy(dx, dy);
      return { x: window.scrollX, y: window.scrollY };
    }, [x, y]);
    if (Math.abs(pos.x - x) < 2 && Math.abs(pos.y - y) < 2) return;
    if (last && pos.x === last.x && pos.y === last.y) {
      // No progress. Give a lazy loader a few rounds to extend the page
      // before concluding it is as tall as it gets.
      stalls++;
      if (stalls >= 3) return;
    } else {
      stalls = 0;
    }
    last = pos;
    await page.waitForTimeout(80);
  }
}

/** Which violations fail an accessibility gate. Embedded from
 *  shared/a11y-rollup.mjs — do not edit here; the app's baseline bookkeeping
 *  uses the same rule and the two must never drift. */
const glazeGateFailures = ${gateFailures.toString()};

/**
 * Accessibility GATE: run axe against the page as it is RIGHT NOW and throw
 * on any new violation at or above "minImpact".
 *
 * "New" means not in the accepted baseline, which arrives as the
 * GLAZE_A11Y_BASELINE env JSON (set by Good Looks! from the test's accepted
 * violations). Outside the app the env is absent, so the gate is at its
 * strictest — every violation at the floor fails. That direction is safe:
 * strictness surfaces findings; the other direction silently passes them.
 *
 * axe is injected here if the per-step capture toggle didn't already inject
 * it: from GLAZE_AXE_PATH when the app is driving, else from a local
 * axe-core install. page.evaluate runs through the driver, so a page CSP
 * cannot block the injection the way it would a script tag.
 */
export async function glazeA11yGate(page, minImpact) {
  const hasAxe = await page.evaluate(() => typeof window.axe !== "undefined");
  if (!hasAxe) {
    const fs = await import("fs");
    let src = null;
    const fromEnv = process.env.GLAZE_AXE_PATH || "";
    if (fromEnv) {
      try { src = fs.readFileSync(fromEnv, "utf8"); } catch (err) { src = null; }
    }
    if (!src) {
      try {
        const { createRequire } = await import("module");
        const req = createRequire(import.meta.url);
        src = fs.readFileSync(req.resolve("axe-core/axe.min.js"), "utf8");
      } catch (err) { src = null; }
    }
    if (!src) {
      throw new Error(
        "Accessibility gate: axe-core was not found. Run from Good Looks!, or npm install axe-core next to this spec.",
      );
    }
    await page.evaluate(src);
  }
  const violations = await page.evaluate(async (caps) => {
    const res = await window.axe.run(document, {
      resultTypes: ["violations"],
      reporter: "v2",
    });
    return (res.violations || []).slice(0, caps.maxViolations).map((v) => ({
      id: v.id,
      impact: v.impact || "minor",
      help: v.help,
      nodes: (v.nodes || []).slice(0, caps.maxNodes).map((n) => (n.target || []).join(" ")),
    }));
  }, { maxViolations: 25, maxNodes: 5 });

  let baseline = [];
  try { baseline = JSON.parse(process.env.GLAZE_A11Y_BASELINE || "[]"); } catch (err) { baseline = []; }
  const failures = glazeGateFailures(violations, minImpact, baseline);
  if (failures.length > 0) {
    const lines = failures.map((f) =>
      "  [" + f.impact + "] " + f.id + (f.help ? " — " + f.help : "") +
      (f.nodes[0] ? " (" + f.nodes.slice(0, 3).join(", ") + ")" : ""),
    );
    throw new Error(
      "Accessibility gate failed — " + failures.length +
      (failures.length === 1 ? " new violation" : " new violations") +
      " at or above \\"" + minImpact + "\\":\\n" + lines.join("\\n"),
    );
  }
}
`;
